name: CustomNPC
version: 2.2.0-dev
main: CustomNPC\Main
api: 5.0.0
author: AlexisV
description: Plugin de NPCs personnalisables avec IA

commands:
  npc:
    description: Commandes NPC admin
    usage: /npc <admin|wand|delete|rotate|armor|list|skin|listskins|debug|refresh|uuid|fakeplayer>
    permission: customnpc.admin
  npcadmin:
    description: Activer le mode admin NPC
    permission: customnpc.admin


permissions:
  customnpc.wand:
    description: Permet d'obtenir la baguette NPC
    default: op
  customnpc.spawn:
    description: Permet de créer un NPC
    default: op
  customnpc.rotate:
    description: Permet de supprimer un NPC
    default: op
  customnpc.armor:
    description: Permet de configurer l'armure d'un NPC
    default: op
  customnpc.list:
    description: Permet de voir la list des ncps
    default: op
  customnpc.uuid:
    description: Permet d'obtenir l'UUID d'un NPC
    default: op
  customnpc.fakeplayer:
    description: Permet de configurer un fake player
    default: op
  customnpc.sudo:
    description: Permet s'utiliser le /sudo
    default: op
  customnpc.admin:
    description: Permet d'activer le mode admin NPC
    default: op

