name: Build PocketMine Plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Dependencies & Inject Virions
        run: |
          composer global require poggit/virion
          composer install --prefer-dist --no-progress

      - name: Build PHAR
        run: |
          poggit-virion build --out=CustomNPC.phar

      - name: Upload PHAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CustomNPC-phar
          path: CustomNPC.phar
